version: "3.9"
services: 
  backend:
    ports:
      - "5006:80"
    environment:
      - APPLICATION_PORT=80
    build:
      context: . 
      dockerfile: ./Vladrega.StreamAlerts/Dockerfile
  frontend:
    ports:
      - "3000:80"
    build:
      context: ./Vladrega.StreamAlerts/ClientApp/my-app
      dockerfile: Dockerfile